spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    driver:
      class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.0.51:3306/payslipreader
    username: 'payslipuser'
    password: 'vE^2b1jY60KP'
  rabbitmq:
    host: 192.168.0.51
    port: 5672
    username: admin
    password: adminpass

#Spring boot actuator properties
management:
  endpoints:
    web:
      exposure:
        include: '*'
        exclude: beans,caches,conditions,configprops,env,loggers
  endpoint:
    health:
      group:
        health-group:
          include: ping,diskSpace
      show-details: ALWAYS
  info:
    env:
      enabled: 'true'
info:
  app:
    name: '@project.name@'
    java:
      version: '@java.version@'
    version: '@project.version@'
    description: '@project.description@'

#Regex configuration
payslip:
  regex:
    baseSalaryRegex: '[YOUR_REGEX_HERE]'
    netSalaryRegex: '[YOUR_REGEX_HERE]'
    totalYearRegex: '[YOUR_REGEX_HERE]'
    dateRegex: '[YOUR_REGEX_HERE]'
    bonusRegex: '[YOUR_REGEX_HERE]'

rico:
  brokerNote:
    operationType: '(?m)^\d+-BOVESPA\s+([CV])\b'
    name: '(?m)^\d+-BOVESPA\s+[CV]\s+\S+\s+(.+?)\s{2,}[A-Z]{4}\d{1,2}'
    ticker: '\b([A-Z]{4}\d{1,2})\b'
    quantity: '\b(\d+)\s+\d+,\d{2}\s+\d+,\d{2}\b'
    price: '\b\d+\s+(\d+,\d{2})\s+\d+,\d{2}\b'
    total: '(?m)^\s*(\d+,\d{2})Valor líquido'
    totalWithTaxes: '(?m)^\s*(\d+,\d{2})Líquido para'
    date: '(?m)^Data pregão\s+(\d{2}/\d{2}/\d{4})'
    bovespa: '1-BOVESPA'