{
 "title": "Payslip Reader App",
 "time": { "from": "2022-12-31T23:00:00.000Z", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 6, "x": 9, "y": 0 },
   "options": {
    "content": "<center><h1>Payslip Reader App Metrics</h1></center>"
   }
  },
  {
   "title": "Heap Used",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 6, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"\", instance=\"payslipapp:8080\", area=\"heap\"})*100/sum(jvm_memory_max_bytes{application=\"\",instance=\"payslipapp:8080\", area=\"heap\"})"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "Application Uptime",
   "gridPos": { "h": 6, "w": 4, "x": 10, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "expr": "process_uptime_seconds{instance=\"payslipapp:8080\", job=\"payslip_reader_app\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Start Time",
   "type": "stat",
   "description": "Application Start Time",
   "gridPos": { "h": 6, "w": 4, "x": 14, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsLocal" } },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "expr": "process_uptime_seconds{instance=\"payslipapp:8080\", job=\"payslip_reader_app\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Find By Month and Year Total Requests",
   "type": "stat",
   "description": "Number of total calls to Find By Month and Year controller endpoint",
   "gridPos": { "h": 5, "w": 4, "x": 7, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_server_requests_seconds_count{uri=\"/payslipReader/findByMonthAndYear\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Response by Code",
   "type": "bargauge",
   "description": "Shows all sort of responses provided by the endpoint.",
   "gridPos": { "h": 5, "w": 6, "x": 11, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_server_requests_seconds_count{uri=\"/payslipReader/findByMonthAndYear\"}",
     "legendFormat": "{{status}} - {{outcome}}"
    }
   ]
  },
  {
   "title": "Create Endpoint Total Requests",
   "type": "stat",
   "description": "Number of total calls to Create controller endpoint",
   "gridPos": { "h": 5, "w": 4, "x": 7, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_server_requests_seconds_count{uri=\"/payslipReader/create\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Response by Code",
   "type": "bargauge",
   "description": "Shows all sort of responses provided by the endpoint.",
   "gridPos": { "h": 5, "w": 6, "x": 11, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_server_requests_seconds_count{uri=\"/payslipReader/create\"}",
     "legendFormat": "{{status}} - {{outcome}}"
    }
   ]
  }
 ]
}