global:
  scrape_interval: 1m
  evaluation_interval: 1m

rule_files:
#  -

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['127.0.0.1:9090']
  - job_name: 'payslip_reader_app'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 1m
    static_configs:
      - targets: ['payslipapp:8080']